api-version: 1.14
name: Bingo
main: Bingo
version: 1.2.4
author: SenorOpi
commands:
  bingo:
    description: General Bingo plugin command
    usage: /bingo
permissions:
  bingo.*:
    description: Gives access to all Bingo comands
    children:
      bingo.admin: true
  bingo.admin:
    description: Allows you to use Bingo admin commands
    default: op